services:
  postgres:
    image: postgres:16
    container_name: auth_postgres
    environment:
      POSTGRES_USER: sudoauth
      POSTGRES_PASSWORD: lolauth
      POSTGRES_DB: lolauthDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sudoauth"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: auth_app
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./private.key:/app/private.key:ro
      - ./public.key:/app/public.key:ro
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  postgres_data:
